### ISSUE TITLE
Question about the evaluation settings.

### ISSUE THREAD

**Issue by CNSaintNeo** [ycszen/TorchSeg#24]
Hi, thanks for you nice work!
But a question still bothers me. Does the single scale performance use the average value of sliding patches cropped in the output, or just use the whole single output to compare with the corresponded same size label?

**Comment by ycszen** [comment]
Actually, I have written two strategies for evaluation  in [here](https://github.com/ycszen/TorchSeg/blob/master/furnace/engine/evaluator.py), including the sliding evaluation and whole evaluation. 
In our experiments, if we focus on the accuracy compared with other state-of-the-art non-real-time algorithms, we use the sliding evaluation strategy. Then if we focus on the speed compared with other real-time methods, we use the whole evaluation strategy, because the sliding-window operation is time-consuming.
